// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.njangui.entity;

import com.test.njangui.entity.Comment;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Comment_Roo_Configurable {
    
    declare @type: Comment: @Configurable;
    
}
